from enum import Enum


class MiddlewaresType(Enum):
    BEFORE_HANDLER = "BEFORE_HANDLER"
    AFTER_HANDLER = "AFTER_HANDLER"
    BEFORE_ENTRY = "BEFORE_ENTRY"
    AFTER_ENTRY = "AFTER_ENTRY"
    BEFORE_EXIT = "BEFORE_EXIT"
    AFTER_EXIT = "AFTER_EXIT"
